In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
df=pd.read_csv("/content/imdb_top_1000.csv")
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
#preprocessing step
df["Genre"]=df["Genre"].fillna("")
df["Overview"]=df["Overview"].fillna("")
df["Content"]=df["Genre"]+" "+df['Overview']

In [ ]:
#TF-IDF Vectorizer
tfidf=TfidfVectorizer(stop_words="english")
tfidf_matrix=tfidf.fit_transform(df["Content"])

In [ ]:
cosine_sim=cosine_similarity(tfidf_matrix,tfidf_matrix)

In [ ]:
#droping the duplicates
indices=pd.Series(df.index,index=df["Series_Title"]).drop_duplicates()

In [ ]:
def recommendation_movie(title,topn=10):
  if title not in indices:
    return "Movie is not found!"
  idx=indices[title]
  sim_scores=list(enumerate(cosine_sim[idx]))
  sim_scores=sorted(sim_scores,key=lambda x:x[1],reverse=True)
  sim_scores=sim_scores[1:topn+1]
  movie_indices=[i[0] for i in sim_scores]
  return df["Series_Title"].iloc[movie_indices]

In [ ]:
recommendation_movie("Inception")

654                     Gattaca
353       Nefes: Vatan Sagolsun
708           À bout de souffle
645             Wo hu cang long
412                   Kagemusha
855              The Odd Couple
238         Munna Bhai M.B.B.S.
884    The Peanut Butter Falcon
893                     Sicario
677                    Predator
Name: Series_Title, dtype: object